FROM node:13.12.0-alpine@sha256:cc85e728fab3827ada20a181ba280cae1f8b625f256e2c86b9094d9bfe834766
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
COPY . ./
RUN npm install
RUN npm install react-scripts@3.4.1 -g
RUN npm ci
RUN npm run build

ENV REACT_APP_API_ENDPOINT=http://127.0.0.1:10003/human_itl
CMD [ "npm", "start" ]
