const analysisInfoActionTypes = {
  GET_CHECKPOINT_DATA: "GET_CHECKPOINT_DATA",
  GET_ANALYSIS_INFO: "GET_ANALYSIS_INFO",
  RESET_ANALYSIS_INFO: "RESET_ANALYSIS_INFO",
  START_PROGRESS: "START_PROGRESS",
  STOP_PROGRESS: "STOP_PROGRESS",
  CONFIRM_ANALYSIS: "CONFIRM_ANALYSIS",
  CONFIRM_INCONCLUSIVE: "CONFIRM_INCONCLUSIVE",
  GET_ANALYSIS_RESULT_LOADING: "GET_ANALYSIS_RESULT_LOADING",
  GET_ANALYSIS_RESULT_SUCCESS: "GET_ANALYSIS_RESULT_SUCCESS",
  GET_ANALYSIS_RESULT_FAILED: "GET_ANALYSIS_RESULT_FAILED"
};

export default analysisInfoActionTypes;