export const analysisActionTypes = {
  GET_ROBOTS_ANALYSIS_SUCCESS: "GET_ROBOTS_ANALYSIS_SUCCESS",
  GET_ROBOTS_ANALYSIS_LOADING: "GET_ROBOTS_ANALYSIS_LOADING",
  GET_ROBOTS_ANALYSIS_FAILED: "GET_ROBOTS_ANALYSIS_FAILED",
  UPDATE_CHECKPOINT_LOADING : "UPDATE_CHECKPOINT_LOADING",
  UPDATE_CHECKPOINT_DATA : "UPDATE_CHECKPOINT_DATA",
  UPDATE_CHECKPOINT_FAILED : "UPDATE_CHECKPOINT_FAILED",
  SET_SUCCESS_RESULT: "SET_SUCCCESS_RESULT",
  
};
